use std::sync::Arc;

use mcp_server_middleware::McpToolCall;
use my_ai_agent::{macros::ApplyJsonSchema, ToolDefinition};
use serde::{Deserialize, Serialize};

use crate::{app_ctx::AppContext, models::ProductId};

const MAX_SECRET_LENGTH: usize = 4096;

#[derive(ApplyJsonSchema, Debug, Serialize, Deserialize)]
pub struct CreateRandomSecretInputData {
    #[property(description: "Product identifier the new secret will belong to. Use \"Shared\" to create a shared secret.")]
    pub product_id: String,

    #[property(description: "Identifier for the secret. When a secret with this id already exists in the given product, nothing is generated and nothing is overwritten — the call succeeds with `created: false`.")]
    pub secret_id: String,

    #[property(description: "How many characters the generated value must have. The value is drawn from [0-9a-zA-Z]. Use 32-64 for passwords and API tokens; shorter values are only for throwaway identifiers.")]
    pub length: usize,

    #[property(description: "Permission level (0-255) the secret is created with. Level gates nested `${...}` resolution: a secret is allowed to reference another secret only when the referenced secret's level is high enough. Pass 0 unless the user asked for a specific level.")]
    pub level: u8,

    #[property(description: "Human-readable description of what the secret is for. Pass empty string if you really have nothing to say (strongly discouraged — descriptions help future agents find the right secret without guessing from the name).")]
    pub description: String,

    #[property(description: "If true, AI can read the generated value back via `get_secret_value`. Keep it false (the default behaviour) for credentials — the generated value stays private and the AI never learns it. Set it to true only when the value must be copied into another system by the AI and the user agreed to that.")]
    pub visible_for_mcp: bool,
}

#[derive(ApplyJsonSchema, Debug, Serialize, Deserialize)]
pub struct CreateRandomSecretResponse {
    #[property(description: "Echoes the product_id of the secret.")]
    pub product_id: String,

    #[property(description: "Echoes the secret_id of the secret.")]
    pub secret_id: String,

    #[property(description: "True when a new secret with a freshly generated random value was stored. False when the secret already existed — in that case nothing was generated and the existing value, level, description and visibility were left untouched.")]
    pub created: bool,

    #[property(description: "Number of characters of the generated value. None when the secret already existed (nothing was generated).")]
    pub generated_length: Option<i32>,

    #[property(description: "Description that is now stored (the freshly stored one when created, the pre-existing one otherwise).")]
    pub description: Option<String>,

    #[property(description: "Permission level that is now stored (the requested one when created, the pre-existing one otherwise).")]
    pub level: i32,

    #[property(description: "Whether the secret is readable via `get_secret_value` (the requested flag when created, the pre-existing one otherwise).")]
    pub visible_for_mcp: bool,
}

pub struct CreateRandomSecretHandler {
    app: Arc<AppContext>,
}

impl CreateRandomSecretHandler {
    pub fn new(app: Arc<AppContext>) -> Self {
        Self { app }
    }
}

impl ToolDefinition for CreateRandomSecretHandler {
    const FUNC_NAME: &'static str = "create_random_secret";
    const DESCRIPTION: &'static str = "Create a secret identified by (product_id, secret_id) whose value is a random string generated by the service — use it for passwords, API tokens, salts and any other credential nobody needs to choose by hand. You specify only `length` and `level`; the value itself is generated server-side from [0-9a-zA-Z] and is NEVER returned by this call (not even when `visible_for_mcp` is true — read it back with `get_secret_value` if you really need it). This call is idempotent and never destructive: when a secret with that id already exists in the product it is left exactly as it is — no new value is generated, nothing is overwritten — and the response comes back with `created: false` plus the metadata of the existing secret. To create a secret with a value you already know, use `create_secret` instead.";
}

#[async_trait::async_trait]
impl McpToolCall<CreateRandomSecretInputData, CreateRandomSecretResponse>
    for CreateRandomSecretHandler
{
    async fn execute_tool_call(
        &self,
        model: CreateRandomSecretInputData,
    ) -> Result<CreateRandomSecretResponse, String> {
        let product_id_input = model.product_id.trim();
        let secret_id = model.secret_id.trim();

        if product_id_input.is_empty() {
            return Err(
                "`product_id` must not be empty (use \"Shared\" for shared secrets)".to_string(),
            );
        }
        if secret_id.is_empty() {
            return Err("`secret_id` must not be empty".to_string());
        }
        if model.length == 0 {
            return Err("`length` must be greater than 0 (use 32-64 for passwords and API tokens)"
                .to_string());
        }
        if model.length > MAX_SECRET_LENGTH {
            return Err(format!(
                "`length` must not exceed {} characters (got {})",
                MAX_SECRET_LENGTH, model.length
            ));
        }

        let lookup_product: ProductId = if product_id_input.eq_ignore_ascii_case("Shared") {
            ProductId::Shared
        } else {
            ProductId::Id(product_id_input)
        };

        let snapshot = self.app.secrets.get_snapshot().await;
        if let Some(existing) = snapshot.get_by_id(lookup_product, secret_id) {
            // The secret is already there - we never overwrite it with a new random value.
            return Ok(CreateRandomSecretResponse {
                product_id: product_id_input.to_string(),
                secret_id: secret_id.to_string(),
                created: false,
                generated_length: None,
                description: existing.description.clone(),
                level: existing.level as i32,
                visible_for_mcp: existing.visible_for_mcp,
            });
        }
        drop(snapshot);

        let secret_value = crate::secret_generator::generate(model.length);

        crate::flows::save_secret(
            self.app.as_ref(),
            lookup_product,
            secret_id.to_string(),
            secret_value,
            None,
            model.level,
            Some(model.description),
            Some(model.visible_for_mcp),
        )
        .await;

        let snapshot = self.app.secrets.get_snapshot().await;
        let stored = snapshot
            .get_by_id(lookup_product, secret_id)
            .ok_or_else(|| {
                format!(
                    "Secret {}/{} was not stored — internal error.",
                    product_id_input, secret_id
                )
            })?;

        Ok(CreateRandomSecretResponse {
            product_id: product_id_input.to_string(),
            secret_id: secret_id.to_string(),
            created: true,
            generated_length: Some(model.length as i32),
            description: stored.description.clone(),
            level: stored.level as i32,
            visible_for_mcp: stored.visible_for_mcp,
        })
    }
}
